### ISSUE TITLE
Pedestrian Detection Datasets

### ISSUE THREAD

**Issue by alpha-carinae29** [neuralet/neuralet#124]
Hi,
We are gathering various surveillance datasets for training pedestrian detection models and evaluating generalization of different approaches.
please list all of these datasets under this issue, thanks

**Comment by alpha-carinae29** [comment]
1. [Oxford Town Center Dataset](https://www.robots.ox.ac.uk/ActiveVision/Research/Projects/2009bbenfold_headpose/project.html)
2. [Caltech Pedestrian Detection](http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/)
3. [Virat Video Dataset](https://viratdata.org/)

**Comment by mhejrati** [comment]
Is this similar to #122 or different?

**Comment by mrn-mln** [comment]
> Is this similar to #122 or different?

Yes, @alpha-carinae29 you can share all videos or available datasets at the mentioned issue by @mhejrati.

**Comment by alpha-carinae29** [comment]
Yeah , sorry for duplication!

**Comment by alpha-carinae29** [comment]
closed

**Comment by alpha-carinae29** [comment]
closed

**Comment by Darlene1213** [comment]
can anyone provide me town center dataset please?? As it is unavailable on the link

**Comment by dreamyt** [comment]
> can anyone provide me town center dataset please?? As it is unavailable on the link

have you gathered the town center dataset? Because now I also need this

**Comment by Xu-Justin** [comment]
> > can anyone provide me town center dataset please?? As it is unavailable on the link
> 
> have you gathered the town center dataset? Because now I also need this

Have you found it @dreamyt? because I also need this, hahaha.

**EDIT**
I collected the dataset and uploaded it to https://www.kaggle.com/datasets/almightyj/oxford-town-centre.

Please keep this in mind as the data was not obtained directly from the official "Oxford Town Centre" dataset. It is possible that the dataset may contain inaccuracies and may not accurately represent the true "Oxford Town Centre" dataset.
